# The book's title. Will be used everywhere!
title: "[Your Book Title]"

# The book's language.
language: en

# Your book copyright info.
# Here's some examples:
#
#   Copyright 2013 by John Doe.
#   Copyright 2013 by John Doe. This work is licensed under MIT License.
#   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
#
copyright: "Copyright (C) 2013 John Doe."

# Who's publishing this book.
publisher: "John Doe"

# When this book was published.
published_at: "2013-06-09"

# Some book description.
subject: "[Your book description]"

# Some keywords that identify this book.
keywords: "[Your book keywords (comma-separated)]"

# Some unique identification. Works great with your domain
# like `http://yourbook.example.com`.
uid: "293e08b213e76ba3520923da2776bc31"

# Your book identification like ISBN or ISSN.
identifier:
  id: "http://yourbook.example.com"
  type: "URL" # can be ISBN, ISSN or URL

# This book authors.
authors:
  - "John Doe"

# The base URL from your source code.
base_url: http://example.com
